version: "3.8"

services:
  # Our NestJS Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      # Only build development stage from Dockerfile in the api
      target: development

    # Mount our host directory to the docker container
    # Mount api directory (./api) to (:) docker container (/usr/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules/

    # RUN in debug mode:  npm run start:debug --> Also start the vscode debugger
    # Run in dev mode: npm run start:dev
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: hard_to_guess_secret_123
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229

  app:
    build:
      dockerfile: Dockerfile
      context: ./app
      target: development

    command: npm run start
    volumes:
      - ./app:/usr/frontend/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
    links:
      - api

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:6.20
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password

    ports:
      - 5050:80
